version: 1.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: nuget restore -DisableParallelProcessing src\SIPSorceryMedia.FFmpeg.csproj
build:
  project: src\SIPSorceryMedia.FFmpeg.csproj
  publish_nuget: false
  verbosity: quiet
after_build:
  - dotnet pack src\SIPSorceryMedia.FFmpeg.csproj -p:NuspecFile=SIPSorceryMedia.FFmpeg.nuspec -c Release --no-build
artifacts:
  - path: '**\*.nupkg'
#  - path: '**\*.snupkg'
deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: aK5GHmF0JAaJZbd7x8g5G2b1qemnimHJMZ5rhQEexHsJJ2B0uVBh/W+KumXETBZz
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*(\.|\.s)nupkg/
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
  - provider: NuGet
    server: https://nuget.pkg.github.com/sipsorcery/index.json
    artifact: /.*(\.|\.s)nupkg/
    username: sipsorcery
    api_key:
      secure: E58r+OknoQn8+bsPRT6l3U2K4kfOpDiGCo1C75LkVg+R/RBHpY//J8UCXEfVvyRB
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
