version: 4.0.{build}
branches:
  except:
    - gh-pages
    - mac-ci
    - ubuntu-ci
    - wsl-ci
environment:
  access_token:
    # Token for github pages publishing.
    secure: 21m76jAVvcu7oACAHFnfCBltcwon+r5ZI3avfRmrNFAqJMn6RfLXwpBhPcJ617tD
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore -DisableParallelProcessing src\SIPSorcery.sln
build:
  project: src\SIPSorcery.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
after_build:
- cmd: ECHO "after_build"
#test:
#  assemblies:
#    only:
#      - SIPSorcery.UnitTests.dll
#    except:
#      - SIPSorcery.IntegrationTests.dll
test_script:
  - dotnet test test/unit/SIPSorcery.UnitTests.csproj -c Release 
on_success:
  - ps: |
        if($env:APPVEYOR_REPO_BRANCH -eq "master" -and -Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git config --global credential.helper store
            Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
            git config --global user.email "aaron@sipsorcery.com"
            git config --global user.name "Aaron Clauson"
            git fetch
            git checkout gh-pages -q
            git merge master
            choco install docfx -y
            & docfx docfx\docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }
            git status
            git add -A
            git commit -am "Appveyor CI updates"
            git push origin gh-pages -q
        }
deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: gmA9IpDL2cCfEbWY0UkUwgnQZwwgiqthE8wgBrybvlbbRwOzWBREoAWqmcyDnEAE
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
    on:
      # branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
  - provider: NuGet
    server: https://nuget.pkg.github.com/sipsorcery/index.json
    artifact: /.*(\.|\.s)nupkg/
    username: sipsorcery
    api_key:
      secure: E58r+OknoQn8+bsPRT6l3U2K4kfOpDiGCo1C75LkVg+R/RBHpY//J8UCXEfVvyRB
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
#  - provider: NuGet
#    server: https://nuget.pkg.github.com/sipsorcery/index.json
#    artifact: /.*(\.|\.s)nupkg/
#    username: sipsorcery
#    api_key:
#      secure: E58r+OknoQn8+bsPRT6l3U2K4kfOpDiGCo1C75LkVg+R/RBHpY//J8UCXEfVvyRB
#    on:
#      APPVEYOR_REPO_TAG: true       # deploy on tag push only
#  - provider: GitHub
#    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#    draft: true
#    prerelease: true
#    auth_token:
#      secure: E58r+OknoQn8+bsPRT6l3U2K4kfOpDiGCo1C75LkVg+R/RBHpY//J8UCXEfVvyRB
#    on:
#      branch: master                # release from master branch only
#      APPVEYOR_REPO_TAG: true       # deploy on tag push only