version: 4.0.{build}
branches:
  except:
    - gh-pages
    - mac-ci
    - win-ci
    - wsl-ci
skip_tags: true
image: ubuntu
environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgZaR7bVAJCsBs/yDlzNbHTvhicc1C7SeyEuVwN+Q0l
init:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
build_script:
- uname -a
- dotnet --version
test_script:
- dotnet test test/unit/SIPSorcery.UnitTests.csproj -c Release --framework netcoreapp3.1
- dotnet test test/unit/SIPSorcery.UnitTests.csproj -c Release --framework net5
#on_finish:
#  - sh: export APPVEYOR_SSH_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -