version: 4.0.{build}
branches:
  except:
    - gh-pages
    - mac-ci
    - ubuntu-ci
    - win-ci
    - wsl-ci
skip_tags: true
image: Visual Studio 2019
before_build:
- cmd: nuget restore -DisableParallelProcessing examples\Softphone\SIPSorcery.SoftPhone.sln
build:
  project: examples\Softphone\SIPSorcery.SoftPhone.sln
  verbosity: minimal