version: 4.0.{build}
branches:
  except:
    - gh-pages
    - mac-ci
    - ubuntu-ci
    - win-ci
    - wsl-ci
skip_tags: true
image: Visual Studio 2019
build_script:
- nuget restore -DisableParallelProcessing examples/sipexamples/sipexamples.sln
- msbuild examples/sipexamples/sipexamples.sln
- nuget restore -DisableParallelProcessing examples/sipexamples/GetStartedNetFramework/GetStartedNetFramework.sln
- msbuild examples/sipexamples/GetStartedNetFramework/GetStartedNetFramework.sln
- nuget restore -DisableParallelProcessing examples/webrtcexamples/webrtcexamples.sln
- msbuild examples/webrtcexamples/webrtcexamples.sln
- nuget restore -DisableParallelProcessing examples/webrtccmdline/webrtccmdline.sln
- msbuild examples/webrtccmdline/webrtccmdline.sln
- nuget restore -DisableParallelProcessing examples/sipcmdline/sipcmdline.sln
- msbuild examples/sipcmdline/sipcmdline.sln
- nuget restore -DisableParallelProcessing examples/stunserver/stunserver.sln
- msbuild examples/stunserver/stunserver.sln